### PR TITLE
Implement a linting pipeline

### PR DESCRIPTION
**Pull request by mehabhalodiya**
# Pull Request Template

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

I have tested this locally, fixed all the warnings and errors that Shellcheck is pointing to, before adding it to the CI and making a PR.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings
- [x] I have tagged the reviewers in a comment below incase my pull request is ready for a review
- [x] I have signed the commit message to agree to Developer Certificate of Origin (DCO) (to certify that you wrote or otherwise have the right to submit your contribution to the project.) by adding "--signoff" to my git commit command.

### CODE REVIEW

**Comment by mehabhalodiya** [comment]
Will anyone help me to resolve this error:
`4:1       warning  truthy value should be one of [false, true]  (truthy)`?

P.S. I have resolved the first warning (you can see in the screenshot provided above) and other errors as well.

**Comment by mehabhalodiya** [comment]
@HarshCasper @Tonnix Will you please have a look at this?
Let me know if any changes are required. I will be happy to improve.
Thank you.

**Comment by asmijafar20** [comment]
It's not successfully built. Failing Prechecks.

**Review by iamrajiv — CHANGES_REQUESTED** [review]
@mehabhalodiya GitHub actions are failing because your code is not following the proper structure. Please update the code with this

```yaml
name: "Lint CI"

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
```

**Review by HarshCasper — CHANGES_REQUESTED** [review]
The CI fails with these:

```sh
Error: ./code/scripts/setup/environment/superscript/superscript.sh:1:1: error: Ensure the shebang uses an absolute path to the interpreter. [SC2239]
Error: ./code/scripts/setup/environment/nodejs/install.sh:2:1: error: The shebang must be on the first line. Delete blanks and move comments. [SC1128]
Error: ./code/scripts/setup/environment/nodejs/uninstall.sh:2:1: error: The shebang must be on the first line. Delete blanks and move comments. [SC1128]
Error: ./code/scripts/setup/environment/jq/install.sh:1:1: error: Tips depend on target shell and yours is unknown. Add a shebang or a 'shell' directive. [SC2148]
Error: ./code/scripts/setup/environment/nano/install.sh:1:1: error: Tips depend on target shell and yours is unknown. Add a shebang or a 'shell' directive. [SC2148]
Error: ./code/scripts/setup/environment/npm/install.sh:1:1: error: Tips depend on target shell and yours is unknown. Add a shebang or a 'shell' directive. [SC2148]
```

Please add another commit in the PR to fix them. Thanks!

**Comment by asmijafar20** [comment]
LGTM.

**Review by HarshCasper — APPROVED** [review]

**Pull request merged**
